Feature/change group list
INSSET/m1_2021_2022-kraken pull request #27
Opened 2022-05-24 20:26 UTC by Midoclas

2022-05-24 20:31 UTC, Hooooki approved these changes

2022-05-25 06:25 UTC, MonsieurMickeNiepceron requested changes
the branch is still not clean

2022-05-25 06:25 UTC, MonsieurMickeNiepceron commented on backend/api/router/groups_routes.py
> +    group_name = request_data['groupName'].encode()
regression

2022-05-25 06:25 UTC, MonsieurMickeNiepceron commented on backend/api/router/groups_routes.py
> +    group_name = request_data['groupName'].encode()
regression

2022-05-30 11:18 UTC, closed without merging